INSERT INTO WetrDB.province (id, name) VALUES (1, 'Burgenland');
INSERT INTO WetrDB.province (id, name) VALUES (2, 'Kärnten');
INSERT INTO WetrDB.province (id, name) VALUES (3, 'Niederösterreich');
INSERT INTO WetrDB.province (id, name) VALUES (4, 'Oberösterreich');
INSERT INTO WetrDB.province (id, name) VALUES (5, 'Salzburg');
INSERT INTO WetrDB.province (id, name) VALUES (6, 'Steiermark');
INSERT INTO WetrDB.province (id, name) VALUES (7, 'Tirol');
INSERT INTO WetrDB.province (id, name) VALUES (8, 'Vorarlberg');
INSERT INTO WetrDB.province (id, name) VALUES (9, 'Wien');