INSERT INTO WetrDB.district (id, name, province_id) VALUES (101, 'Eisenstadt(Stadt)', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (102, 'Rust(Stadt)', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (103, 'Eisenstadt-Umgebung', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (104, 'Güssing', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (105, 'Jennersdorf', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (106, 'Mattersburg', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (107, 'Neusiedl am See', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (108, 'Oberpullendorf', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (109, 'Oberwart', 1);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (201, 'Klagenfurt Stadt', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (202, 'Villach Stadt', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (203, 'Hermagor', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (204, 'Klagenfurt Land', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (205, 'Sankt Veit an der Glan', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (206, 'Spittal an der Drau', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (207, 'Villach Land', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (208, 'Völkermarkt', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (209, 'Wolfsberg', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (210, 'Feldkirchen', 2);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (301, 'Krems an der Donau(Stadt)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (302, 'Sankt Pölten(Stadt)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (303, 'Waidhofen an der Ybbs(Stadt)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (304, 'Wiener Neustadt(Stadt)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (305, 'Amstetten', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (306, 'Baden', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (307, 'Bruck an der Leitha', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (308, 'Gänserndorf', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (309, 'Gmünd', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (310, 'Hollabrunn', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (311, 'Horn', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (312, 'Korneuburg', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (313, 'Krems(Land)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (314, 'Lilienfeld', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (315, 'Melk', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (316, 'Mistelbach', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (317, 'Mödling', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (318, 'Neunkirchen', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (319, 'Sankt Pölten(Land)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (320, 'Scheibbs', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (321, 'Tulln', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (322, 'Waidhofen an der Thaya', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (323, 'Wiener Neustadt(Land)', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (325, 'Zwettl', 3);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (401, 'Linz(Stadt)', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (402, 'Steyr(Stadt)', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (403, 'Wels(Stadt)', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (404, 'Braunau am Inn', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (405, 'Eferding', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (406, 'Freistadt', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (407, 'Gmunden', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (408, 'Grieskirchen', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (409, 'Kirchdorf an der Krems', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (410, 'Linz-Land', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (411, 'Perg', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (412, 'Ried im Innkreis', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (413, 'Rohrbach', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (414, 'Schärding', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (415, 'Steyr-Land', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (416, 'Urfahr-Umgebung', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (417, 'Vöcklabruck', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (418, 'Wels-Land', 4);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (501, 'Salzburg(Stadt)', 5);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (502, 'Hallein', 5);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (503, 'Salzburg-Umgebung', 5);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (504, 'Sankt Johann im Pongau', 5);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (505, 'Tamsweg', 5);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (506, 'Zell am See', 5);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (601, 'Graz(Stadt)', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (603, 'Deutschlandsberg', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (606, 'Graz-Umgebung', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (610, 'Leibnitz', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (611, 'Leoben', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (612, 'Liezen', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (614, 'Murau', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (616, 'Voitsberg', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (617, 'Weiz', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (620, 'Murtal', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (621, 'Bruck-Mürzzuschlag', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (622, 'Hartberg-Fürstenfeld', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (623, 'Südoststeiermark', 6);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (701, 'Innsbruck-Stadt', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (702, 'Imst', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (703, 'Innsbruck-Land', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (704, 'Kitzbühel', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (705, 'Kufstein', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (706, 'Landeck', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (707, 'Lienz', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (708, 'Reutte', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (709, 'Schwaz', 7);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (801, 'Bludenz', 8);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (802, 'Bregenz', 8);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (803, 'Dornbirn', 8);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (804, 'Feldkirch', 8);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (900, 'Wien(Stadt)', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (901, 'Wien  1.,Innere Stadt', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (902, 'Wien  2.,Leopoldstadt', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (903, 'Wien  3.,Landstraße', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (904, 'Wien  4.,Wieden', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (905, 'Wien  5.,Margareten', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (906, 'Wien  6.,Mariahilf', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (907, 'Wien  7.,Neubau', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (908, 'Wien  8.,Josefstadt', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (909, 'Wien  9.,Alsergrund', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (910, 'Wien 10.,Favoriten', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (911, 'Wien 11.,Simmering', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (912, 'Wien 12.,Meidling', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (913, 'Wien 13.,Hietzing', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (914, 'Wien 14.,Penzing', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (915, 'Wien 15.,Rudolfsheim-Fünfhaus', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (916, 'Wien 16.,Ottakring', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (917, 'Wien 17.,Hernals', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (918, 'Wien 18.,Währing', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (919, 'Wien 19.,Döbling', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (920, 'Wien 20.,Brigittenau', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (921, 'Wien 21.,Floridsdorf', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (922, 'Wien 22.,Donaustadt', 9);
INSERT INTO WetrDB.district (id, name, province_id) VALUES (923, 'Wien 23.,Liesing', 9);